### Class EDA RTT-36

In [38]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [39]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

In [40]:
raw_df = pd.read_csv('data/RTT_36_data.csv')

df = raw_df.copy()
df

,ID,Start time,Completion time,Email,Name,Last modified time,What is your cohort number?,What month did your cohort start?,What year is it?,What is your age?,What is your gender?,What's you dominant hand?,Do you prefer sweet or salty snacks?,How many siblings do you have?,What state do you live in?,What time zone are you in?,What language do you speak most often at home?,What other languages can you speak or understand?,What month were you born?,Do you prefer calling or texting?,What season do you enjoy the most?,What best describes you?,How many people live in your household (including you?,How many pets do you have?,How many hours of sleep do you usually get each night?,Which best describes you right now?,What industry do you currently work in (or most recently worked in)?\n,How many years have you worked?,How many hours each week do you plan to study for this course?,Have you ever taken an online course before?,What OS are you using?,Which browser do you use the most?,How comfortable are you learning new technology?,About how many hours per day do you spend using a computer?,About how many hours a day do you spend on your phone?,What AI tools have you used?,"Have you ever written computer code before (python, sql, c, JS, Java, ect...)?",Which social media platforms do you use regularly?,What hobbies do you enjoy?,How often do you exercise?,Do you enjoy cooking?,"Coffee, tea, both, neither?",Approximately how many books did you read last year?,Which music genres do you enjoy?,Which movie or TV genres do you enjoy?,What streaming services do you subscribe to?,"Are you a dog person, cat person, both, or neither?",Does pineapple belong on pizza?,What is your favorite color?,What destination would you choose?,Favorite board / card game?,Favorite video game?,Favorite movie?,Favorite TV show?,What is your favorite sport to watch or play?
0,1,8/4/26 11:47:47,8/4/26 11:53:02,anonymous,NaN,NaN,2026-RTT-36,August,2026,36,Male,Right,Sweet,0,OH,Eastern,Vietnamese,English;,November,Texting,Spring,Early Bird,4,85,7,Self-employed?,Education,16,15,Yes,Windows,Chrome,5,10,1-2,ChatGPT;Copilot;Gemini;Claude;Perplexity;,No,Facebook;LinkedIn;,Reading;Photography;Building / Making Things;C...,5+ times/week,Yes,Both,1-2,Country;Classical;,Adventure;,Netflix;Youtube;,Neither,5.0,Green,Mountains,monopoly,NaN,avengers,Harry potter,badminton
1,2,8/4/26 11:48:01,8/4/26 11:53:11,anonymous,NaN,NaN,2026 RTT-36,August,2026,38,Female,Right,Sweet,1,Ohio,Eastern,English,NaN,July,Calling,Spring,Afternoon Duck,6,1,7,Student,Healthcare,18,10,Yes,Windows,Chrome,5,8,2,ChatGPT;Copilot;Claude;Gemini;Perplexity;,No,Instagram;Facebook;,Reading;Writing / Journaling;Photography;Playi...,5+ times/week,Sometimes,Both,5,Jazz;Rap;Classical;R & B;,"Reality;Action, comedy;",Netflix;Youtube;Hulu;,Both,1.0,Green,National Park,uno,Mario Kart,Friday,Blackish,Basketball
2,3,8/4/26 11:47:53,8/4/26 11:53:12,anonymous,NaN,NaN,36,August,2026,28,Female,Right,Sweet,2,Michigan,Eastern,English,Spanish;,July,Texting,Fall,Night Owl,4,1,5-6,Working full-time,Technology,10,15,Yes,MacOS,Chrome,5,12,4,Copilot;Gemini;Claude;,Yes,Instagram;,Reading;Writing / Journaling;Photography;Actin...,3-4 times/week,Sometimes,Neither,2,Jazz;R & B;Rap;Lofi;,Anime;Drama;,Netflix;Hulu;HBO;Paramount;,Both,5.0,Blue,Mountains,Uno,Pac Man,The Shack,Avatar the Last Airbender,Tennis
3,4,8/4/26 11:48:01,8/4/26 11:54:22,anonymous,NaN,NaN,2026-rtt-36,August,2026,37,Male,Right,Salty,2,michigan,Eastern,english,English;French;Arabic;,April,Texting,Fall,dolphin,4,0,6,Looking for work,controls engineer,13,7,Yes,Windows,Chrome,5,10,1-2,ChatGPT;Copilot;Gemini;Claude;deepseek;,Yes,LinkedIn;Tik Tok;Instagram;Snapchat;,Building / Making Things;Home Improvement;Vide...,1-2 times/week,Sometimes,Both,1,Country;Classical;pop;,Thriller;Fantasy;scifi;,Netflix;mobilvids;,Both,5.0,Green,Countryside,monopoly,Tempest Rising,Bicentennial man,super natural,"Gold, Play"
4,5,8/4/26 11:48:32,8/4/26 11:54:34,anonymous,NaN,NaN,2026-RTT-36,August,2026,27,Male,Right,Salty,2,Missouri,Central,Telugu,English;Telugu;,January,Calling,Spring,Night Owl,1,0,7,Looking for work,Technology,3,8,Yes,Windows,Chrome,5,6,5,ChatGPT;Copilot;Gemini;Claude;,Yes,Instagram;LinkedIn;,Reading;Photography;Playing Music / Singing;Co...,1-2 times/week,Yes,Tea,0,Rap;Jazz;,Thriller;Reality;Drama;,Netflix;Youtube;,Dog,3.0,White,Beach,UNO,God of war,Kantara,Young Sheldon,Cricket
5,6,8/4/26 11:47:42,8/4/26 11:54:51,anonymous,NaN,NaN,2026 - RTT -36,August,2026,41,Female,Right,Salty,1,Michigan,Eastern,Urdu,English;German;Arabic;Hindi;Gujrati;,July,Texting,Spring,Early Bird,7,0,6,Student,Healthcare,10,15,Yes,Windows,Edge,5,8,1,Gemini;Copilot;Claude;ChatGPT;Perplexity;Deeps...,Yes,Facebook;,Reading;Drawing / Painting;Building / Making T...,1-2 times/week,Yes,Coffee,3,NaN,Documentary;,NaN,Neither,5.0,Yellow,Beach,NaN,NaN,NaN,NaN,Tennis
6,7,8/4/26 11:48:14,8/4/26 11:55:29,anonymous,NaN,NaN,36,August,2026,46,Male,Right,Salty,4,Michigan,Eastern,English,English;Spanish;,January,Texting,Fall,Night Owl,2,1,6,Off on Disability,Healthcare,32 years,10,Yes,MacOS,Safari,5,3,8,ChatGPT;Gemini;Claude;Perplexity;,Yes,Instagram;Facebook;LinkedIn;Snapchat;Twitter / X;,Reading;Drawing / Painting;Photography;Crafts ...,Never,Yes,Tea,2,Rock;Punk;Jazz;Country;Rap;Classical;R & B;,Thriller;Horror;Drama;Fantasy;Reality;Document...,Hulu;HBO;,Both,5.0,Black,Beach,Monopoly,Skyrim elder scrolls,Living Out Loud,Sex and the city,basketball
7,8,8/4/26 11:48:06,8/4/26 11:55:42,anonymous,NaN,NaN,2026-RTT-36,August,2026,38,Female,Right,Sweet,5,Michighan,Eastern,English,French;,October,Calling,Fall,Afternoon Duck,2,0,8,Student,Real Estate,6,23,Yes,Windows,Edge,5,2,3,ChatGPT;,No,Facebook;,Reading;Drawing / Painting;Playing Music / Sin...,1-2 times/week,Yes,Both,3,Jazz;Classical;,Documentary;,Netflix;,Neither,5.0,Green,Countryside,puzzle,no,no,no,soccer
8,9,8/4/26 11:48:08,8/4/26 11:55:59,anonymous,NaN,NaN,36,August,2026,31,Female,Right,Sweet,1,Ohio,Eastern,English,Portuguese;Spanish;,November,Texting,Summer,Night Owl,6,1,6,Self-employed?,Retail & E-commerce,12,10-12,Yes,Windows,Chrome,5,8,2,ChatGPT;Gemini;Perplexity;,No,Instagram;Facebook;LinkedIn;Tik Tok;Reddit;,Drawing / Painting;Building / Making Things;Cr...,3-4 times/week,Sometimes,Coffee,3,"Rock;Heavy Metal;Indie, folk, alternative;R & B;",Fantasy;Thriller;Drama;Documentary;,Netflix;Hulu;HBO;Peacock;Disney;,Dog,3.0,Green,Mountains,What Do You Meme,Mario Kart,The Pianist,Schitts Creek,"Watch soccer, play volleyball"
9,10,8/4/26 11:47:49,8/4/26 11:56:16,anonymous,NaN,NaN,RTT-36,August,2026,23,Male,Left,Sweet,8,Missouri,Central,English,Spanish;English;,October,Texting,Fall,Night Owl,5,3,6-8 hours,Student,Retail & E-commerce,6,10-20 hours,Yes,MacOS,Chrome,5,3 hours,4 hours,Claude;ChatGPT;,Yes,Tik Tok;,Playing Music / Singing;Drawing / Painting;Cod...,3-4 times/week,Yes,Tea,3,R & B;Rap;,Drama;Fantasy;Action and SCI-FI;,Netflix;Paramount;Hulu;HBO;Prime ;,Dog,2.0,Brown,Big City,Monopoly,Call of Duty,Lion King,Spongebob,Basketball
10,11,8/4/26 11:48:47,8/4/26 11:56:51,anonymous,NaN,NaN,2026-RTT-36,August,2026,38,Female,Right,Sweet,1,Ohio,Eastern,English,English;,September,Texting,Spring,Early Bird,2,1,7,Self-employed?,Real Estate,6,11,Yes,MacOS,Chrome,4,9,3,ChatGPT;Gemini;Claude;,Yes,Instagram;Tik Tok;LinkedIn;,Reading;Photography;Building / Making Things;C...,1-2 times/week,Sometimes,Neither,1,Rap;R & B;Gospel;Jazz;,Thriller;Drama;Reality;Documentary;,Netflix;HBO;Peacock;,Both,2.0,Purple,Beach,uno,mario,twilight,not sure,football
11,12,8/4/26 11:48:01,8/4/26 11:57:12,anonymous,NaN,NaN,2026-RT-36,August,2026,45,Male,Right,Salty,1,Missouri,Central,Russian,English;Greek;,October,Texting,Summer,Afternoon Duck,1,0,7,Self-employed?,Education,20,20,Yes,Windows,Edge,5,8,6,ChatGPT;Gemini;Claude;,Yes,Facebook;Tik Tok;,Reading;Crafts / DIY Projects;Building / Makin...,5+ times/week,Yes,Coffee,20,Rock;Heavy Metal;Classical;R & B;,Thriller;Drama;Fantasy;Documentary;,Netflix;Hulu;,Cat,1.0,Red,Beach,monopoly,Assassin Creed,Casablanca,Jack Richard,Athletics
12,13,8/4/26 11:47:51,8/4/26 11:58:21,anonymous,NaN,NaN,2026-RTT-36,August,2026,39,Female,Left,Salty,5,Missouri,Central,English,Spanish;,May,Texting,Spring,Night Owl,4,1,6,Student,Finance and Banking,20,12,Yes,Windows,Edge,5,10,5,ChatGPT;Copilot;Gemini;Claude;,Yes,Tik Tok;Facebook;Instagram;Snapchat;Twitter / ...,Reading;Crafts / DIY Projects;Playing Music / ...,3-4 times/week,Yes,Both,2,R & B;Bachata;Rap;Country;Rock;,Thriller;Horror;Fantasy;,"Paramount;Peacock;HBO;Hulu;Netflix;Prime, Star...",Neither,1.0,Green,Beach,Taboo,Mortal Kombat,Last Samurai,Game of Thrones,Football
13,14,8/4/26 11:47:42,8/4/26 11:58:51,anonymous,NaN,NaN,2026-RTT-36,August,2026,32,Male,Ambidexterous,Sweet,12,Michigan,Eastern,English,NaN,December,Calling,Fall,Mixture of the three,1,0,5-6,"Self-employed, working part-time, & student",Arts & Creative Industries,7,15,Yes,MacOS,Safari,5,3,5,ChatGPT;Gemini;,Yes,Instagram;Facebook;LinkedIn;,Drawing / Painting;Photography;Cooking;Baking;...,3-4 times/week,Sometimes,Tea,10 completed 0,Rap;Jazz;R & B;Classical;,Crime;Drama;Thriller;Anime;Fantasy;Reality;Doc...,Netflix;Hulu;,Neither,5.0,Black,Beach,Spades,UFC,You Got Served,Bernie Mac Show,Rugby
14,15,8/4/26 11:47:44,8/4/26 12:00:34,anonymous,NaN,NaN,2026-rtt-36,August,2026,39,Female,Right,Salty,2,Michigan,Eastern,Urdu and English,English;Hindi;Telugu;,August,Texting,Summer,Early Bird,5,5,7,Looking for work,Healthcare,3,15-17,Yes,Windows,Chrome,5,8,1-2,ChatGPT;,Yes,LinkedIn;,Drawing / Painting;Crafts / DIY Projects;Build...,1-2 times/week,NaN,Both,2,Classical;,Anime;,Netflix;,Neither,5.0,Orange,Beach,Sequence,No,Indian/Bahubali,NaN,Badminton
15,16,8/4/26 11:47:46,8/4/26 12:00:39,anonymous,NaN,NaN,2026-rtt-36,August,2026,40,Male,Ambidexterous,Salty,1,Missouri,Central,English,English;,July,Texting,Fall,Early Bird,6,0,6 hours,Student,Arts & Creative Industries,24 years,10 hours,Yes,Windows,Chrome,4,8 hours,4 hours,ChatGPT;Gemini;Claude;,No,Instagram;Facebook;,Reading;Cooking;Writing / Journaling;Playing M...,3-4 times/week,Yes,NaN,3,Rock;Rap;R & B;Jazz;,Anime;Thriller;Horror;Fantasy;Reality;Document...,Netflix;Youtube;,Dog,NaN,Blue,Beach,UNO,Mortal Kombat,Matrix,Walking Dead,MMA
16,17,8/4/26 11:47:54,8/4/26 12:00:59,anonymous,NaN,NaN,36,August,2026,25,Female,Right,Sweet,3,Ohio,Eastern,Nepali (my mother language),English;Hindi;,June,Texting,Spring,Night Owl,3,no pet,7 hours,Working part-time,Retail & E-commerce,2 years,15 - 20 hours,Yes,Windows,Chrome,5,minimum 2 hours,3 - 4 hours,ChatGPT;Gemini;,Yes,Instagram;,Reading;Writing / Journaling;Drawing / Paintin...,1-2 times/week,Yes,Neither,1 book a year,Rock;,Horror;Thriller;Documentary;,Netflix;Youtube;,Neither,1.0,Purple,Mountains,"chess, badminton",Pub G,The pursuit of happiness,none,"football, wrestling"
17,18,8/4/26 11:47:47,8/4/26 12:01:40,anonymous,NaN,NaN,2026-RTT-36,August,2026,37,Female,Right,Salty,1,Ohio,Eastern,Spanish,English;Spanish;Portuguese;,November,Texting,Summer,Early Bird,2,0,7,Looking for work,Technology,7,6,Yes,MacOS,Chrome,5,2,3,Gemini;ChatGPT;,Yes,Instagram;Facebook;Tik Tok;LinkedIn;,Reading;Crafts / DIY Projects;Dancing;Cooking;...,3-4 times/week,Yes,Coffee,2,Jazz;Rap;Mexican Music;Bachata;Classical;,Drama;Documentary;Reality;,Netflix;,Neither,5.0,Green,Mountains,UNO,NaN,Avatar,gilmore girls,soccer
18,19,8/4/26 11:48:16,8/4/26 12:01:51,anonymous,NaN,NaN,2026-RTT-36,August,2026,33,Male,Right,Sweet,2,Missouri,Central,English,Yoruba;,September,Texting,Summer,Night Owl,2,0,6,Student,Technology,5,10,Yes,Windows,Chrome,4,5,10,ChatGPT;Copilot;Gemini;,No,LinkedIn;Instagram;,Photography;Watching Movies;Sports (Watching);...,1-2 times/week,Sometimes,Tea,1,Classical;R & B;Country;,Documentary;Fantasy;,Peacock;Paramount;,Dog,1.0,Green,Big City,Ludo,God of War,White Chicks,Loki,Soccer
19,20,8/4/26 11:48:06,8/4/26 12:02:43,anonymous,NaN,NaN,2026-rrt-36,August,2026,50,Male,Right,Salty,0,Ohio,Eastern,English,Indonesia;,April,Calling,Fall,Night Owl,5,2,6,Student,Technology,15,15,Yes,Windows,Chrome,5,8,12,ChatGPT;Claude;Gemini;,Yes,Instagram;Facebook;Twitter / X;Tik Tok;LinkedIn;,Reading;Writing / Journaling;Playing Music / S...,1-2 times/week,Yes,Coffee,0,Country;Jazz;R & B;Pop;,Horror;Drama;Fantasy;Thriller;,Netflix;Hulu;Youtube;,Cat,5.0,Green,Beach,NaN,NaN,Titanic,I mostly watch YouTube.,Soccer
20,21,8/4/26 11:47:42,8/4/26 12:03:37,anonymous,NaN,NaN,2026-36,August,2026,42,Female,Right,Sweet,2,Ohio,Eastern,English,Spanish;,October,Calling,Fall,Early Bird,1,0,4,Looking for work,HR,25,15,Yes,Windows,Chrome,5,12,5,ChatGPT;Copilot;Gemini;Claude;,Yes,Instagram;LinkedIn;Twitter / X;Tik Tok;,Reading;Playing Music / Singing;Watching TV Sh...,Never,Sometimes,Both,100,Rap;Classical;R & B;Jazz;Country;Rock;Pop;,Drama;Reality;Documentary;Fantasy;Thriller;Act...,Netflix;Hulu;Paramount;HBO;Disney;,Neither,4.0,Black,National Park,UNO,Mario Brothers,Malcom X,Martin,NaN
21,22,8/4/26 11:47:45,8/4/26 12:03:49,anonymous,NaN,NaN,2026-rtt-36,August,2026,45,Male,Right,Sweet,3,MO,Central,english,NaN,November,Calling,Fall,Early Bird,8,0,6,Working part-time,Hospitality & Tourism,3,10,Yes,MacOS,Internet Explorer,5,8,8,ChatGPT;Copilot;Claude;,Yes,Facebook;Twitter / X;Tik Tok;,Writing / Journaling;Building / Making Things;...,3-4 times/week,Yes,Both,8,Jazz;R & B;,Drama;Reality;,"Netflix;Hulu;foxOne, roku, prime, ;",Cat,4.0,Black,Big City,chess,none,not sure,NaN,soccer and tennis
22,23,8/4/26 11:47:44,8/4/26 12:04:15,anonymous,NaN,NaN,2026-rtt-36,August,2026,38,Female,Right,Salty,5,ohio,Eastern,arabic,English;Arabic;somali;,August,Texting,Fall,Early Bird,4,none,7,Student,Healthcare,10,12,No,Windows,Internet Explorer,3,8,16,ChatGPT;Gemini;,No,Instagram;LinkedIn;Facebook;Snapchat;Tik Tok;,Puzzles;Sports (Watching);Reading;Playing Musi...,3-4 times/week,Yes,Coffee,5,R & B;,Drama;,Netflix;Hulu;Peacock;,Neither,1.0,Green,Beach,Uno and Solitaire,Candy Crush Saga,"The Notebook , Inception , and White Chicks",Scandal and This is us,Soccer
23,24,8/4/26 11:47:44,8/4/26 12:05:03,anonymous,NaN,NaN,2026-RTT-36,August,2026,38,Male,Right,Sweet,5,MO,Central,English,Spanish;ASL;,September,Calling,Summer,Night Owl,2,0,5,Self-employed?,transportation,10,10-12,Yes,Windows,Chrome,3,2,4,"ChatGPT;heygen,base44,meta ai;",Yes,Instagram;Facebook;,Reading;Photography;Playing Music / Singing;Co...,3-4 times/week,Yes,Both,3,Jazz;Rap;R & B;Rock;,Reality;Thriller;Drama;Documentary;,Netflix;Hulu;Youtube;,Dog,1.0,Blue,Beach,monopoly,2k,black panther,billions,boxing
24,25,8/4/26 11:47:52,8/4/26 12:17:23,anonymous,NaN,NaN,2026-RT-36,August,2026,44,Male,Right,Sweet,4,Missouri,Central,English,English;,May,Calling,Fall,A bit of an early bird Night owl,one (just myself),NaN,6 to 7,Working full-time,Non-profit & Charity,20 plus years,3 to 5 hours each week,Yes,Windows,Edge,4,8 to 10 hours,17-20 hours a day,"ChatGPT;Gemini;Claude;Suno, Sora, Meta AI;",No,Instagram;Facebook;Snapchat;LinkedIn;Twitter /...,Reading;Writing / Journaling;Drawing / Paintin...,1-2 times/week,Yes,Tea,4,Rap;Rock;Country;R & B;,Anime;Thriller;Horror;Drama;Fantasy;Reality;Do...,"None, I'm not subscribed to any of those strea...",Both,2.0,Black,Big City,"Spades, UNO",Madden Football and Soul Caliber,"Stomp The yard, You Got Served, Saw","America's Best Dance Crew, So You Think You Ca...",Football and Basketball
25,26,8/4/26 11:48:02,8/4/26 12:38:12,anonymous,NaN,NaN,2026-RTT-36,August,2026,63,Female,Right,Sweet,1,Michigan,Eastern,English,NaN,August,Texting,Winter,Wolf,4,0,4,Disability,Healthcare,40,30,Yes,Windows,Chrome,4,12,12,ChatGPT;Copilot;Gemini;,No,Facebook;Instagram;LinkedIn;Twitter / X;Tik To...,Building / Making Things;Home Improvement;Lear...,Never,No,Both,NaN,Rock;Punk;Jazz;Country;Heavy Metal;Folk;,Fantasy;Drama;Thriller;Romance;,Amazon Prime;,Both,5.0,Orange,Mountains,Solitaire,NaN,Fifth-Element,Reacher,Snowboarding
26,27,8/4/26 11:47:50,8/4/26 12:50:19,anonymous,NaN,NaN,2026-rtt-36,August,2026,32,Female,Right,Salty,0,OH,Eastern,Twi,English;,October,Texting,Summer,Night Owl,4,0,6,Working full-time,Retail & E-commerce,3,15,Yes,Windows,Chrome,5,16,5,ChatGPT;Copilot;Gemini;Perplexity;,Yes,Instagram;LinkedIn;Facebook;Reddit;,Reading;Dancing;Playing Music / Singing;Puzzle...,3-4 times/week,No,Tea,0,Country;Rock;Jazz;Classical;R & B;,Anime;Thriller;Drama;Horror;Fantasy;Comedy;,Netflix;Prime;,Neither,3.0,Blue,National Park,Non,Non,Empire Waist,Arrested Development,Soccer
27,28,8/4/26 12:58:33,8/4/26 13:01:35,anonymous,NaN,NaN,RTT-36,August,2026,19,Male,Right,Sweet,3,Michigan,Eastern,Bengali,English;Arabic;,May,Texting,Fall,Early Bird,6,0,6,Student,Retail & E-commerce,2,9,Yes,Windows,Chrome,5,8,5,ChatGPT;Gemini;Claude;Perplexity;,No,Instagram;LinkedIn;,Reading;Sports (Playing);,5+ times/week,No,Coffee,0,None;,None;,None;,Cat,4.0,Blue,Mountains,Monopoly,COD mobile,Scooby Doo,Henry Danger,Running
28,29,8/4/26 13:07:43,8/4/26 13:14:10,anonymous,NaN,NaN,2026-RTT-36,August,2026,34,Female,Right,Sweet,0,Ohio,Eastern,English,English;,August,Texting,Winter,Night Owl,4,1,6-7 hours,Working part-time,Hospitality & Tourism,16,15-20,Yes,MacOS,Safari/Firefox,4,10-15,3-4,ChatGPT;,Yes,Instagram;LinkedIn;Tik Tok;,Reading;Writing / Journaling;Drawing / Paintin...,3-4 times/week,Sometimes,Coffee,16,R & B;Jazz;Classical;,Romantic/Comedy;,NaN,Dog,5.0,Green,Beach,Sorry,Bomberman Hero,A Walk to Remember,NaN,"Basketball, Flag Football"

In [41]:
# Shape
rows, cols = df.shape
print(f'Rows: {rows}')
print(f'Cols: {cols}')

Rows: 29
Cols: 55

In [42]:
# Head
df.head()

,ID,Start time,Completion time,Email,Name,Last modified time,What is your cohort number?,What month did your cohort start?,What year is it?,What is your age?,What is your gender?,What's you dominant hand?,Do you prefer sweet or salty snacks?,How many siblings do you have?,What state do you live in?,What time zone are you in?,What language do you speak most often at home?,What other languages can you speak or understand?,What month were you born?,Do you prefer calling or texting?,What season do you enjoy the most?,What best describes you?,How many people live in your household (including you?,How many pets do you have?,How many hours of sleep do you usually get each night?,Which best describes you right now?,What industry do you currently work in (or most recently worked in)?\n,How many years have you worked?,How many hours each week do you plan to study for this course?,Have you ever taken an online course before?,What OS are you using?,Which browser do you use the most?,How comfortable are you learning new technology?,About how many hours per day do you spend using a computer?,About how many hours a day do you spend on your phone?,What AI tools have you used?,"Have you ever written computer code before (python, sql, c, JS, Java, ect...)?",Which social media platforms do you use regularly?,What hobbies do you enjoy?,How often do you exercise?,Do you enjoy cooking?,"Coffee, tea, both, neither?",Approximately how many books did you read last year?,Which music genres do you enjoy?,Which movie or TV genres do you enjoy?,What streaming services do you subscribe to?,"Are you a dog person, cat person, both, or neither?",Does pineapple belong on pizza?,What is your favorite color?,What destination would you choose?,Favorite board / card game?,Favorite video game?,Favorite movie?,Favorite TV show?,What is your favorite sport to watch or play?
0,1,8/4/26 11:47:47,8/4/26 11:53:02,anonymous,NaN,NaN,2026-RTT-36,August,2026,36,Male,Right,Sweet,0,OH,Eastern,Vietnamese,English;,November,Texting,Spring,Early Bird,4,85,7,Self-employed?,Education,16,15,Yes,Windows,Chrome,5,10,1-2,ChatGPT;Copilot;Gemini;Claude;Perplexity;,No,Facebook;LinkedIn;,Reading;Photography;Building / Making Things;C...,5+ times/week,Yes,Both,1-2,Country;Classical;,Adventure;,Netflix;Youtube;,Neither,5.0,Green,Mountains,monopoly,NaN,avengers,Harry potter,badminton
1,2,8/4/26 11:48:01,8/4/26 11:53:11,anonymous,NaN,NaN,2026 RTT-36,August,2026,38,Female,Right,Sweet,1,Ohio,Eastern,English,NaN,July,Calling,Spring,Afternoon Duck,6,1,7,Student,Healthcare,18,10,Yes,Windows,Chrome,5,8,2,ChatGPT;Copilot;Claude;Gemini;Perplexity;,No,Instagram;Facebook;,Reading;Writing / Journaling;Photography;Playi...,5+ times/week,Sometimes,Both,5,Jazz;Rap;Classical;R & B;,"Reality;Action, comedy;",Netflix;Youtube;Hulu;,Both,1.0,Green,National Park,uno,Mario Kart,Friday,Blackish,Basketball
2,3,8/4/26 11:47:53,8/4/26 11:53:12,anonymous,NaN,NaN,36,August,2026,28,Female,Right,Sweet,2,Michigan,Eastern,English,Spanish;,July,Texting,Fall,Night Owl,4,1,5-6,Working full-time,Technology,10,15,Yes,MacOS,Chrome,5,12,4,Copilot;Gemini;Claude;,Yes,Instagram;,Reading;Writing / Journaling;Photography;Actin...,3-4 times/week,Sometimes,Neither,2,Jazz;R & B;Rap;Lofi;,Anime;Drama;,Netflix;Hulu;HBO;Paramount;,Both,5.0,Blue,Mountains,Uno,Pac Man,The Shack,Avatar the Last Airbender,Tennis
3,4,8/4/26 11:48:01,8/4/26 11:54:22,anonymous,NaN,NaN,2026-rtt-36,August,2026,37,Male,Right,Salty,2,michigan,Eastern,english,English;French;Arabic;,April,Texting,Fall,dolphin,4,0,6,Looking for work,controls engineer,13,7,Yes,Windows,Chrome,5,10,1-2,ChatGPT;Copilot;Gemini;Claude;deepseek;,Yes,LinkedIn;Tik Tok;Instagram;Snapchat;,Building / Making Things;Home Improvement;Vide...,1-2 times/week,Sometimes,Both,1,Country;Classical;pop;,Thriller;Fantasy;scifi;,Netflix;mobilvids;,Both,5.0,Green,Countryside,monopoly,Tempest Rising,Bicentennial man,super natural,"Gold, Play"
4,5,8/4/26 11:48:32,8/4/26 11:54:34,anonymous,NaN,NaN,2026-RTT-36,August,2026,27,Male,Right,Salty,2,Missouri,Central,Telugu,English;Telugu;,January,Calling,Spring,Night Owl,1,0,7,Looking for work,Technology,3,8,Yes,Windows,Chrome,5,6,5,ChatGPT;Copilot;Gemini;Claude;,Yes,Instagram;LinkedIn;,Reading;Photography;Playing Music / Singing;Co...,1-2 times/week,Yes,Tea,0,Rap;Jazz;,Thriller;Reality;Drama;,Netflix;Youtube;,Dog,3.0,White,Beach,UNO,God of war,Kantara,Young Sheldon,Cricket

In [43]:
# Tail
df.tail()

,ID,Start time,Completion time,Email,Name,Last modified time,What is your cohort number?,What month did your cohort start?,What year is it?,What is your age?,What is your gender?,What's you dominant hand?,Do you prefer sweet or salty snacks?,How many siblings do you have?,What state do you live in?,What time zone are you in?,What language do you speak most often at home?,What other languages can you speak or understand?,What month were you born?,Do you prefer calling or texting?,What season do you enjoy the most?,What best describes you?,How many people live in your household (including you?,How many pets do you have?,How many hours of sleep do you usually get each night?,Which best describes you right now?,What industry do you currently work in (or most recently worked in)?\n,How many years have you worked?,How many hours each week do you plan to study for this course?,Have you ever taken an online course before?,What OS are you using?,Which browser do you use the most?,How comfortable are you learning new technology?,About how many hours per day do you spend using a computer?,About how many hours a day do you spend on your phone?,What AI tools have you used?,"Have you ever written computer code before (python, sql, c, JS, Java, ect...)?",Which social media platforms do you use regularly?,What hobbies do you enjoy?,How often do you exercise?,Do you enjoy cooking?,"Coffee, tea, both, neither?",Approximately how many books did you read last year?,Which music genres do you enjoy?,Which movie or TV genres do you enjoy?,What streaming services do you subscribe to?,"Are you a dog person, cat person, both, or neither?",Does pineapple belong on pizza?,What is your favorite color?,What destination would you choose?,Favorite board / card game?,Favorite video game?,Favorite movie?,Favorite TV show?,What is your favorite sport to watch or play?
24,25,8/4/26 11:47:52,8/4/26 12:17:23,anonymous,NaN,NaN,2026-RT-36,August,2026,44,Male,Right,Sweet,4,Missouri,Central,English,English;,May,Calling,Fall,A bit of an early bird Night owl,one (just myself),NaN,6 to 7,Working full-time,Non-profit & Charity,20 plus years,3 to 5 hours each week,Yes,Windows,Edge,4,8 to 10 hours,17-20 hours a day,"ChatGPT;Gemini;Claude;Suno, Sora, Meta AI;",No,Instagram;Facebook;Snapchat;LinkedIn;Twitter /...,Reading;Writing / Journaling;Drawing / Paintin...,1-2 times/week,Yes,Tea,4,Rap;Rock;Country;R & B;,Anime;Thriller;Horror;Drama;Fantasy;Reality;Do...,"None, I'm not subscribed to any of those strea...",Both,2.0,Black,Big City,"Spades, UNO",Madden Football and Soul Caliber,"Stomp The yard, You Got Served, Saw","America's Best Dance Crew, So You Think You Ca...",Football and Basketball
25,26,8/4/26 11:48:02,8/4/26 12:38:12,anonymous,NaN,NaN,2026-RTT-36,August,2026,63,Female,Right,Sweet,1,Michigan,Eastern,English,NaN,August,Texting,Winter,Wolf,4,0,4,Disability,Healthcare,40,30,Yes,Windows,Chrome,4,12,12,ChatGPT;Copilot;Gemini;,No,Facebook;Instagram;LinkedIn;Twitter / X;Tik To...,Building / Making Things;Home Improvement;Lear...,Never,No,Both,NaN,Rock;Punk;Jazz;Country;Heavy Metal;Folk;,Fantasy;Drama;Thriller;Romance;,Amazon Prime;,Both,5.0,Orange,Mountains,Solitaire,NaN,Fifth-Element,Reacher,Snowboarding
26,27,8/4/26 11:47:50,8/4/26 12:50:19,anonymous,NaN,NaN,2026-rtt-36,August,2026,32,Female,Right,Salty,0,OH,Eastern,Twi,English;,October,Texting,Summer,Night Owl,4,0,6,Working full-time,Retail & E-commerce,3,15,Yes,Windows,Chrome,5,16,5,ChatGPT;Copilot;Gemini;Perplexity;,Yes,Instagram;LinkedIn;Facebook;Reddit;,Reading;Dancing;Playing Music / Singing;Puzzle...,3-4 times/week,No,Tea,0,Country;Rock;Jazz;Classical;R & B;,Anime;Thriller;Drama;Horror;Fantasy;Comedy;,Netflix;Prime;,Neither,3.0,Blue,National Park,Non,Non,Empire Waist,Arrested Development,Soccer
27,28,8/4/26 12:58:33,8/4/26 13:01:35,anonymous,NaN,NaN,RTT-36,August,2026,19,Male,Right,Sweet,3,Michigan,Eastern,Bengali,English;Arabic;,May,Texting,Fall,Early Bird,6,0,6,Student,Retail & E-commerce,2,9,Yes,Windows,Chrome,5,8,5,ChatGPT;Gemini;Claude;Perplexity;,No,Instagram;LinkedIn;,Reading;Sports (Playing);,5+ times/week,No,Coffee,0,None;,None;,None;,Cat,4.0,Blue,Mountains,Monopoly,COD mobile,Scooby Doo,Henry Danger,Running
28,29,8/4/26 13:07:43,8/4/26 13:14:10,anonymous,NaN,NaN,2026-RTT-36,August,2026,34,Female,Right,Sweet,0,Ohio,Eastern,English,English;,August,Texting,Winter,Night Owl,4,1,6-7 hours,Working part-time,Hospitality & Tourism,16,15-20,Yes,MacOS,Safari/Firefox,4,10-15,3-4,ChatGPT;,Yes,Instagram;LinkedIn;Tik Tok;,Reading;Writing / Journaling;Drawing / Paintin...,3-4 times/week,Sometimes,Coffee,16,R & B;Jazz;Classical;,Romantic/Comedy;,NaN,Dog,5.0,Green,Beach,Sorry,Bomberman Hero,A Walk to Remember,NaN,"Basketball, Flag Football"

In [44]:
# Datatypes
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 55 columns):
 #   Column                                                                          Non-Null Count  Dtype
---  ------                                                                          --------------  -----
 0   ID                                                                              29 non-null     int64
 1   Start time                                                                      29 non-null     str
 2   Completion time                                                                 29 non-null     str
 3   Email                                                                           29 non-null     str
 4   Name                                                                            0 non-null      float64
 5   Last modified time                                                              0 non-null      float64
 6   What is your cohort number?                                                     29 non-null     str
 7   What month did your cohort start?                                               29 non-null     str
 8   What year is it?                                                                29 non-null     int64
 9   What is your age?                                                               29 non-null     int64
 10  What is your gender?                                                            29 non-null     str
 11  What's you dominant hand?                                                       29 non-null     str
 12  Do you prefer sweet or salty snacks?                                            29 non-null     str
 13  How many siblings do you have?                                                  29 non-null     int64
 14  What state do you live in?                                                      29 non-null     str
 15  What time zone are you in?                                                      29 non-null     str
 16  What language do you speak most often at home?                                  29 non-null     str
 17  What other languages can you speak or understand?                               25 non-null     str
 18  What month were you born?                                                       29 non-null     str
 19  Do you prefer calling or texting?                                               29 non-null     str
 20  What season do you enjoy the most?                                              29 non-null     str
 21  What best describes you?                                                        29 non-null     str
 22  How many people live in your household (including you?                          29 non-null     str
 23  How many pets do you have?                                                      28 non-null     str
 24  How many hours of sleep do you usually get each night?                          29 non-null     str
 25  Which best describes you right now?                                             29 non-null     str
 26  What industry do you currently work in (or most recently worked in)?
           29 non-null     str
 27  How many years have you worked?                                                 29 non-null     str
 28  How many hours each week do you plan to study for this course?                  29 non-null     str
 29  Have you ever taken an online course before?                                    29 non-null     str
 30  What OS are you using?                                                          29 non-null     str
 31  Which browser do you use the most?                                              29 non-null     str
 32  How comfortable are you learning new technology?                                29 non-null     int64
 33  About how many hours per day do you spend using a computer?                     29 non-null     str
 34  About how many hours a day do you spend on your phone?                          29 non-null     str
 35  What AI tools have you used?                                                    29 non-null     str
 36  Have you ever written computer code before (python, sql, c, JS, Java, ect...)?  29 non-null     str
 37  Which social media platforms do you use regularly?                              29 non-null     str
 38  What hobbies do you enjoy?                                                      29 non-null     str
 39  How often do you exercise?                                                      29 non-null     str
 40  Do you enjoy cooking?                                                           28 non-null     str
 41  Coffee, tea, both, neither?                                                     28 non-null     str
 42  Approximately how many books did you read last year?                            28 non-null     str
 43  Which music genres do you enjoy?                                                28 non-null     str
 44  Which movie or TV genres do you enjoy?                                          29 non-null     str
 45  What streaming services do you subscribe to?                                    27 non-null     str
 46  Are you a dog person, cat person, both, or neither?                             29 non-null     str
 47  Does pineapple belong on pizza?                                                 28 non-null     float64
 48  What is your favorite color?                                                    29 non-null     str
 49  What destination would you choose?                                              29 non-null     str
 50  Favorite board / card game?                                                     27 non-null     str
 51  Favorite video game?                                                            24 non-null     str
 52  Favorite movie?                                                                 28 non-null     str
 53  Favorite TV show?                                                               25 non-null     str
 54  What is your favorite sport to watch or play?                                   28 non-null     str
dtypes: float64(3), int64(5), str(47)
memory usage: 12.6 KB

In [45]:
# Descriptive stats
df.describe()

,ID,Name,Last modified time,What year is it?,What is your age?,How many siblings do you have?,How comfortable are you learning new technology?,Does pineapple belong on pizza?
count,29.000000,0.0,0.0,29.0,29.000000,29.000000,29.000000,28.000000
mean,15.000000,NaN,NaN,2026.0,37.172414,2.655172,4.655172,3.357143
std,8.514693,NaN,NaN,0.0,8.705782,2.635958,0.613879,1.704336
min,1.000000,NaN,NaN,2026.0,19.000000,0.000000,3.000000,1.000000
25%,8.000000,NaN,NaN,2026.0,32.000000,1.000000,4.000000,1.750000
50%,15.000000,NaN,NaN,2026.0,38.000000,2.000000,5.000000,4.000000
75%,22.000000,NaN,NaN,2026.0,41.000000,4.000000,5.000000,5.000000
max,29.000000,NaN,NaN,2026.0,63.000000,12.000000,5.000000,5.000000

In [46]:
# Missing Values
df.isnull().sum()

ID                                                                                 0
Start time                                                                         0
Completion time                                                                    0
Email                                                                              0
Name                                                                              29
Last modified time                                                                29
What is your cohort number?                                                        0
What month did your cohort start?                                                  0
What year is it?                                                                   0
What is your age?                                                                  0
What is your gender?                                                               0
What's you dominant hand?                                                          0
Do you prefer sweet or salty snacks?                                               0
How many siblings do you have?                                                     0
What state do you live in?                                                         0
What time zone are you in?                                                         0
What language do you speak most often at home?                                     0
What other languages can you speak or understand?                                  4
What month were you born?                                                          0
Do you prefer calling or texting?                                                  0
What season do you enjoy the most?                                                 0
What best describes you?                                                           0
How many people live in your household (including you?                             0
How many pets do you have?                                                         1
How many hours of sleep do you usually get each night?                             0
Which best describes you right now?                                                0
What industry do you currently work in (or most recently worked in)?\n             0
How many years have you worked?                                                    0
How many hours each week do you plan to study for this course?                     0
Have you ever taken an online course before?                                       0
What OS are you using?                                                             0
Which browser do you use the most?                                                 0
How comfortable are you learning new technology?                                   0
About how many hours per day do you spend using a computer?                        0
About how many hours a day do you spend on your phone?                             0
What AI tools have you used?                                                       0
Have you ever written computer code before (python, sql, c, JS, Java, ect...)?     0
Which social media platforms do you use regularly?                                 0
What hobbies do you enjoy?                                                         0
How often do you exercise?                                                         0
Do you enjoy cooking?                                                              1
Coffee, tea, both, neither?                                                        1
Approximately how many books did you read last year?                               1
Which music genres do you enjoy?                                                   1
Which movie or TV genres do you enjoy?                                             0
What streaming services do you subscribe to?                                       2
Are you a dog person, cat person, both, or neither?                                0
Does pineapple belong on pizza?                                                    1
What is your favorite color?                                                       0
What destination would you choose?                                                 0
Favorite board / card game?                                                        2
Favorite video game?                                                               5
Favorite movie?                                                                    1
Favorite TV show?                                                                  4
What is your favorite sport to watch or play?                                      1
dtype: int64

In [47]:
# Duplicates
df.duplicated().sum()

np.int64(0)

### Problems with the data set:

- Varying data types in columns
- Data type conversions
- Columns that are empty
- Missing information in several columns
- Multiple values in single columns
- Emails are all anonymous (remove?)
- make column names easier to use

In [48]:
# Rename columns
new_columns = [
    "response_id",
    "start_time",
    "completion_time",
    "email",
    "name",
    "last_modified_time",
    "cohort_id",
    "cohort_start_month",
    "cohort_start_year",
    "age",
    "gender",
    "dominant_hand",
    "snack_preference",
    "sibling_count",
    "state",
    "time_zone",
    "primary_home_language",
    "other_languages",
    "birth_month",
    "communication_preference",
    "favorite_season",
    "chronotype",
    "household_size",
    "pet_count",
    "sleep_hours",
    "employment_status",
    "industry",
    "years_worked",
    "weekly_study_hours",
    "online_course_experience",
    "operating_system",
    "primary_browser",
    "tech_learning_confidence",
    "daily_computer_hours",
    "daily_phone_hours",
    "ai_tools_used",
    "prior_coding_experience",
    "social_media_platforms",
    "hobbies",
    "exercise_frequency",
    "cooking_interest",
    "beverage_preference",
    "books_read_last_year",
    "music_genres",
    "movie_tv_genres",
    "streaming_services",
    "pet_person_preference",
    "pineapple_pizza_rating",
    "favorite_color",
    "preferred_destination",
    "favorite_board_card_game",
    "favorite_video_game",
    "favorite_movie",
    "favorite_tv_show",
    "favorite_sport",
]

In [49]:
df.columns = new_columns
df.columns

Index(['response_id', 'start_time', 'completion_time', 'email', 'name',
       'last_modified_time', 'cohort_id', 'cohort_start_month',
       'cohort_start_year', 'age', 'gender', 'dominant_hand',
       'snack_preference', 'sibling_count', 'state', 'time_zone',
       'primary_home_language', 'other_languages', 'birth_month',
       'communication_preference', 'favorite_season', 'chronotype',
       'household_size', 'pet_count', 'sleep_hours', 'employment_status',
       'industry', 'years_worked', 'weekly_study_hours',
       'online_course_experience', 'operating_system', 'primary_browser',
       'tech_learning_confidence', 'daily_computer_hours', 'daily_phone_hours',
       'ai_tools_used', 'prior_coding_experience', 'social_media_platforms',
       'hobbies', 'exercise_frequency', 'cooking_interest',
       'beverage_preference', 'books_read_last_year', 'music_genres',
       'movie_tv_genres', 'streaming_services', 'pet_person_preference',
       'pineapple_pizza_rating', 'favorite_color', 'preferred_destination',
       'favorite_board_card_game', 'favorite_video_game', 'favorite_movie',
       'favorite_tv_show', 'favorite_sport'],
      dtype='str')

In [50]:
# Drop unecessary columns
df = df.drop(columns=[
    "start_time",
    "completion_time",
    "email",
    "name",
    "last_modified_time",
    'cohort_id',
    'cohort_start_month',
    'cohort_start_year'
])

df.columns

Index(['response_id', 'age', 'gender', 'dominant_hand', 'snack_preference',
       'sibling_count', 'state', 'time_zone', 'primary_home_language',
       'other_languages', 'birth_month', 'communication_preference',
       'favorite_season', 'chronotype', 'household_size', 'pet_count',
       'sleep_hours', 'employment_status', 'industry', 'years_worked',
       'weekly_study_hours', 'online_course_experience', 'operating_system',
       'primary_browser', 'tech_learning_confidence', 'daily_computer_hours',
       'daily_phone_hours', 'ai_tools_used', 'prior_coding_experience',
       'social_media_platforms', 'hobbies', 'exercise_frequency',
       'cooking_interest', 'beverage_preference', 'books_read_last_year',
       'music_genres', 'movie_tv_genres', 'streaming_services',
       'pet_person_preference', 'pineapple_pizza_rating', 'favorite_color',
       'preferred_destination', 'favorite_board_card_game',
       'favorite_video_game', 'favorite_movie', 'favorite_tv_show',
       'favorite_sport'],
      dtype='str')

### Data Changes:

- years_worked (int)
- sleep_hours (int)
- weekly_study_hours (int)
- household_size (int)
- pet_count (int)

In [ ]:
df['years_worked'].value_counts()

years_worked
10                4
3                 4
6                 3
16                2
20                2
7                 2
18                1
13                1
32 years          1
12                1
24 years          1
2 years           1
5                 1
15                1
25                1
20 plus years     1
40                1
2                 1
Name: count, dtype: int64

In [52]:
df['years_worked'] = pd.to_numeric(
    df['years_worked'].astype('string').str.extract(r'(\d+(?:\.\d+)?)', expand=False),
    errors='coerce'
)

In [54]:
df['sleep_hours'].value_counts()

sleep_hours
6             10
7              8
5-6            2
4              2
8              1
6-8 hours      1
6 hours        1
7 hours        1
5              1
6 to 7         1
6-7 hours      1
Name: count, dtype: int64

In [55]:
import re

def convert_range(value):
    """Convert a number or numeric range to a float; ranges become their average."""
    if pd.isna(value):
        return np.nan

    numbers = re.findall(r"\d+(?:\.\d+)?", str(value))
    if not numbers:
        return np.nan

    return float(np.mean([float(number) for number in numbers]))

df["sleep_hours"] = df["sleep_hours"].apply(convert_range)

In [56]:
df['sleep_hours'].value_counts()

sleep_hours
6.0    11
7.0    10
5.5     2
4.0     2
6.5     2
8.0     1
5.0     1
Name: count, dtype: int64

In [57]:
# - weekly_study_hours (int)
# - household_size (int)
# - pet_count (int)

columns_to_fix = ['weekly_study_hours', 'household_size', 'pet_count']

for val in columns_to_fix:
    df[val] = df[val].apply(convert_range)

In [58]:
df[['weekly_study_hours', 'household_size', 'pet_count']].head()

   weekly_study_hours  household_size  pet_count
0                15.0             4.0       85.0
1                10.0             6.0        1.0
2                15.0             4.0        1.0
3                 7.0             4.0        0.0
4                 8.0             1.0        0.0